environment.yml: Pin torchvision
Pins torchvision to 0.11.3 since the latest 0.12.0 version throws an exception `ImportError: cannot import name QuantStub from torch.ao.quantization torch/ao/quantization/__init__.py` when running `from fastbook import *`